Repository digitalfabrik/integreat-cms, pull requests merged in 2022-03, with the labels that each got.

#1260 Fix Firebase Notifications
  CHANGELOG.md
  integreat_cms/api/urls.py
  integreat_cms/cms/migrations/0008_alter_pushnotification_channel.py
  integreat_cms/cms/views/push_notifications/push_notification_sender.py
  integreat_cms/core/settings.py
Labels: prio: high

#1265 Fix creating language tree nodes
  integreat_cms/api/v3/events.py
  integreat_cms/api/v3/pages.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/custom_tree_node_form.py
  integreat_cms/cms/forms/language_tree/language_tree_node_form.py
  integreat_cms/cms/forms/pages/page_form.py
  integreat_cms/cms/models/abstract_content_model.py
  integreat_cms/cms/models/abstract_tree_node.py
  integreat_cms/cms/models/pages/page.py
  integreat_cms/cms/models/pages/page_translation.py
  integreat_cms/cms/models/push_notifications/push_notification.py
  integreat_cms/cms/templates/language_tree/language_tree_node_form.html
  integreat_cms/cms/views/analytics/translation_coverage_view.py
  integreat_cms/cms/views/pages/page_tree_view.py
  integreat_cms/cms/views/pages/partial_page_tree_view.py
  integreat_cms/cms/views/pois/poi_list_view.py
  integreat_cms/cms/views/push_notifications/push_notification_list_view.py
  integreat_cms/cms/views/utils/search_content_ajax.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/cms/views/view_config.py
Labels: prio: high

#1262 Deploy fixed region cloning, FCM messages, page form & translation status
  CHANGELOG.md
  integreat_cms/api/urls.py
  integreat_cms/api/v3/events.py
  integreat_cms/api/v3/pages.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/custom_tree_node_form.py
  integreat_cms/cms/forms/language_tree/language_tree_node_form.py
  integreat_cms/cms/forms/pages/page_form.py
  integreat_cms/cms/forms/regions/region_form.py
  integreat_cms/cms/migrations/0008_alter_pushnotification_channel.py
  integreat_cms/cms/migrations/0009_alter_translation_model_ordering.py
  integreat_cms/cms/models/abstract_base_model.py
  integreat_cms/cms/models/abstract_content_model.py
  integreat_cms/cms/models/abstract_tree_node.py
  integreat_cms/cms/models/events/event_translation.py
  integreat_cms/cms/models/languages/language_tree_node.py
  integreat_cms/cms/models/pages/imprint_page_translation.py
  integreat_cms/cms/models/pages/page.py
  integreat_cms/cms/models/pages/page_translation.py
  integreat_cms/cms/models/pois/poi_translation.py
  integreat_cms/cms/models/push_notifications/push_notification.py
  integreat_cms/cms/models/push_notifications/push_notification_translation.py
  integreat_cms/cms/models/users/user.py
  integreat_cms/cms/templates/language_tree/language_tree_node_form.html
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/cms/views/analytics/translation_coverage_view.py
  integreat_cms/cms/views/dashboard/region_selection.py
  integreat_cms/cms/views/events/event_form_view.py
  integreat_cms/cms/views/pages/page_form_view.py
  integreat_cms/cms/views/pages/page_tree_view.py
  integreat_cms/cms/views/pages/partial_page_tree_view.py
  integreat_cms/cms/views/pois/poi_form_view.py
  integreat_cms/cms/views/pois/poi_list_view.py
  integreat_cms/cms/views/push_notifications/push_notification_list_view.py
  integreat_cms/cms/views/push_notifications/push_notification_sender.py
  integreat_cms/cms/views/utils/search_content_ajax.py
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/api/api_config.py
  tests/api/expected-outputs/augsburg_de_locations.json
  tests/api/expected-outputs/nurnberg_ar_fcm.json
  tests/api/expected-outputs/nurnberg_de_fcm.json
  tests/api/expected-outputs/nurnberg_en_fcm.json
  tests/cms/region_test.py
  tests/cms/views/view_config.py
Labels: prio: high

#1267 Fix push notifications attribute name in API
  CHANGELOG.md
  integreat_cms/api/v3/regions.py
  tests/api/expected-outputs/regions.json
  tests/api/expected-outputs/regions_live.json
Labels: prio: high

#1273 Add traceback spoiler to bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: prio: low

#1272 Fix feedback endpoint
  CHANGELOG.md
  integreat_cms/api/v3/feedback/event_feedback.py
  integreat_cms/api/v3/feedback/page_feedback.py
  integreat_cms/api/v3/feedback/poi_feedback.py
  integreat_cms/cms/fixtures/test_data.json
  tests/api/expected-outputs/api_augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_children.json
  tests/api/expected-outputs/augsburg_de_events.json
  tests/api/expected-outputs/augsburg_de_locations.json
  tests/api/expected-outputs/augsburg_de_page_1.json
  tests/api/expected-outputs/augsburg_de_pages.json
Labels: prio: high

#1246 Add push page API end point, fixes #1099
  CHANGELOG.md
  dev-tools/install.sh
  integreat_cms/api/urls.py
  integreat_cms/api/v3/pages.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/pages/page_form.py
  integreat_cms/cms/migrations/0010_page_api_token.py
  integreat_cms/cms/models/pages/page.py
  integreat_cms/cms/templates/pages/page_form.html
  integreat_cms/cms/views/pages/page_form_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/pages/page-api-token.ts
  package-lock.json
  package.json
  sphinx/continuous-integration.rst
  sphinx/installation.rst
  tests/api/api_config.py
  tests/api/api_test.py
  tests/api/expected-outputs/augsburg_de_pushpage_invalid.json
  tests/api/expected-outputs/augsburg_de_pushpage_valid.json
Labels: prio: low

#1278 Fix XLIFF import
  CHANGELOG.md
  integreat_cms/cms/models/pages/abstract_base_page_translation.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/xliff/utils.py
  tests/xliff/__init__.py
  tests/xliff/dummy_django_app/__init__.py
  tests/xliff/dummy_django_app/static_urls.py
  tests/xliff/files/export/augsburg_de_en_1_2_willkommen.xliff
  tests/xliff/files/export/augsburg_de_en_2_1_willkommen-in-augsburg.xliff
  tests/xliff/files/import/augsburg_de_en_1_2_willkommen.xliff
  tests/xliff/files/import/augsburg_de_en_2_1_willkommen-in-augsburg.xliff
  tests/xliff/xliff_test.py
Labels: prio: high

#1291 Update bumpver, xhtml2pdf & other pip dependencies
  CHANGELOG.md
  Pipfile.lock
Labels: prio: high

#1266 Parallel testing & code coverage reporting
  .circleci/config.yml
  .pylintrc
  Pipfile
  Pipfile.lock
  dev-tools/test.sh
  dev-tools/test_cov.sh
  sphinx/dev-tools.rst
  tests/api/api_config.py
  tests/api/expected-outputs/augsburg_de_pushpage_invalid.json
  tests/api/expected-outputs/augsburg_de_pushpage_valid.json
  tests/api/test_api_feedback.py
  tests/api/test_api_push_page.py
  tests/api/test_api_result.py
  tests/cms/test_duplicate_regions.py
  tests/cms/views/status_code/__init__.py
  tests/cms/views/status_code/test_view_status_code_1.py
  tests/cms/views/status_code/test_view_status_code_10.py
  tests/cms/views/status_code/test_view_status_code_11.py
  tests/cms/views/status_code/test_view_status_code_12.py
  tests/cms/views/status_code/test_view_status_code_13.py
  tests/cms/views/status_code/test_view_status_code_14.py
  tests/cms/views/status_code/test_view_status_code_15.py
  tests/cms/views/status_code/test_view_status_code_16.py
  tests/cms/views/status_code/test_view_status_code_2.py
  tests/cms/views/status_code/test_view_status_code_3.py
  tests/cms/views/status_code/test_view_status_code_4.py
  tests/cms/views/status_code/test_view_status_code_5.py
  tests/cms/views/status_code/test_view_status_code_6.py
  tests/cms/views/status_code/test_view_status_code_7.py
  tests/cms/views/status_code/test_view_status_code_8.py
  tests/cms/views/status_code/test_view_status_code_9.py
  tests/cms/views/test_public_view_status_code.py
  tests/cms/views/test_view_redirect.py
  tests/cms/views/utils.py
  tests/cms/views/view_config.py
  tests/cms/views/view_test.py
Labels: prio: low

#1286 Improve push notifications handling
  CHANGELOG.md
  dev-tools/_functions.sh
  integreat_cms/cms/models/push_notifications/push_notification_translation.py
  integreat_cms/cms/templates/_base.html
  integreat_cms/cms/templates/push_notifications/push_notification_form.html
  integreat_cms/cms/templates/push_notifications/push_notification_list.html
  integreat_cms/cms/templates/push_notifications/push_notification_list_row.html
  integreat_cms/cms/templatetags/push_notification_filters.py
  integreat_cms/cms/views/push_notifications/push_notification_form_view.py
  integreat_cms/cms/views/push_notifications/push_notification_list_view.py
  integreat_cms/cms/views/push_notifications/push_notification_sender.py
  integreat_cms/core/circleci_settings.py
  integreat_cms/core/context_processors.py
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/cms/views/view_config.py
Labels: prio: medium

#1287 Fix feedback cache invalidation
  CHANGELOG.md
  integreat_cms/cms/apps.py
  integreat_cms/cms/signals/__init__.py
  integreat_cms/cms/signals/feedback_signals.py
  integreat_cms/cms/views/feedback/admin_feedback_actions.py
  integreat_cms/cms/views/feedback/region_feedback_actions.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: prio: low

#1135 Add automatic translations via DeepL API
  CHANGELOG.md
  Pipfile.lock
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/bulk_action_views.py
  integreat_cms/core/settings.py
  integreat_cms/deepl_api/__init__.py
  integreat_cms/deepl_api/utils.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  setup.cfg
Labels: prio: low

#1261 Implement lock for content editing
  CHANGELOG.md
  integreat_cms/cms/forms/custom_content_model_form.py
  integreat_cms/cms/models/abstract_content_model.py
  integreat_cms/cms/models/pages/imprint_page.py
  integreat_cms/cms/templates/_content_edit_lock.html
  integreat_cms/cms/templates/events/event_form.html
  integreat_cms/cms/templates/generic_confirmation_dialog.html
  integreat_cms/cms/templates/imprint/imprint_form.html
  integreat_cms/cms/templates/pages/page_form.html
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/cms/templatetags/text_filters.py
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/utils/content_edit_lock.py
  integreat_cms/cms/views/events/event_form_view.py
  integreat_cms/cms/views/imprint/imprint_form_view.py
  integreat_cms/cms/views/mixins.py
  integreat_cms/cms/views/pages/page_form_view.py
  integreat_cms/cms/views/pois/poi_form_view.py
  integreat_cms/cms/views/utils/__init__.py
  integreat_cms/cms/views/utils/content_edit_lock.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/confirmation-popups.ts
  integreat_cms/static/src/js/content-edit-lock.ts
  integreat_cms/static/src/js/forms/autosave.ts
  integreat_cms/static/src/js/forms/tinymce-init.ts
  integreat_cms/static/src/js/unsaved-warning.ts
Labels: prio: medium
