Repository digitalfabrik/integreat-cms, pull requests merged in 2023-11, with the labels that each got.

#2515 Fix "in total" in dashboard
  integreat_cms/cms/views/dashboard/dashboard_view.py
Labels: prio: high

#2499 Fix crashing dashboard when region has no default language
  integreat_cms/cms/templates/dashboard/dashboard.html
  integreat_cms/cms/views/dashboard/dashboard_view.py
Labels: bug

#2513 Fix page archive message
  integreat_cms/cms/views/bulk_action_views.py
  integreat_cms/cms/views/utils/__init__.py
  integreat_cms/cms/views/utils/stringify_list.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2478.yml
Labels: prio: low
