Repository digitalfabrik/integreat-cms, pull requests merged in 2023-07, with the labels that each got.

#2331 [Obdach] Add new icons for poicategory
  integreat_cms/cms/constants/poicategory.py
  integreat_cms/cms/migrations/0072_alter_poicategory_icon.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2270.yml
  integreat_cms/static/src/svg/poi-category-icons/advice.svg
  integreat_cms/static/src/svg/poi-category-icons/daily_routine.svg
  integreat_cms/static/src/svg/poi-category-icons/finance.svg
  integreat_cms/static/src/svg/poi-category-icons/medical_aid.svg
  integreat_cms/static/src/svg/poi-category-icons/other_help.svg
  integreat_cms/static/src/svg/poi-category-icons/structure.svg
Labels: prio: urgent

#2328 Add website field to organization
  docs/src/api-docs.rst
  integreat_cms/api/v3/locations.py
  integreat_cms/api/v3/pages.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/organizations/organization_form.py
  integreat_cms/cms/migrations/0073_add_organization_website.py
  integreat_cms/cms/models/users/organization.py
  integreat_cms/cms/templates/organizations/organization_form.html
  integreat_cms/cms/templates/organizations/organization_list.html
  integreat_cms/cms/templates/organizations/organization_list_row.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2325.yml
  tests/api/expected-outputs/augsburg_ar_locations.json
  tests/api/expected-outputs/augsburg_ar_pages.json
  tests/api/expected-outputs/augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_locations.json
  tests/api/expected-outputs/augsburg_de_pages.json
  tests/api/expected-outputs/augsburg_en_locations.json
  tools/loadtestdata.sh
Labels: prio: high

#2373 Fix Push Notification Problems
  integreat_cms/cms/forms/push_notifications/push_notification_form.py
  integreat_cms/cms/models/push_notifications/push_notification.py
  integreat_cms/cms/templates/push_notifications/push_notification_form.html
  integreat_cms/cms/views/push_notifications/push_notification_form_view.py
  integreat_cms/core/management/commands/send_push_notifications.py
  integreat_cms/core/middleware/region_middleware.py
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: bug, prio: high
