Repository digitalfabrik/integreat-cms, pull requests merged in 2024-12, with the labels that each got.

#3127 Disallow publishing imported events through version history
  integreat_cms/cms/templates/content_versions.html
  integreat_cms/cms/views/content_version_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: prio: high

#3255 Adjust link type wording (follow up for #3191)
  integreat_cms/cms/constants/linkcheck.py
  integreat_cms/cms/templates/analytics/_broken_links_widget.html
  integreat_cms/cms/templates/linkcheck/links_by_filter.html
  integreat_cms/cms/views/linkcheck/linkcheck_list_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: effort: low

#3229 Fix some problems with outlook recurrence rule
  integreat_cms/cms/utils/external_calendar_utils.py
  tests/cms/utils/assets/calendars/invalid_recurrence_rule_bymonth.ics
  tests/cms/utils/assets/calendars/invalid_recurrence_rule_bymonthday.ics
  tests/cms/utils/assets/calendars/invalid_recurrence_rule_wkst_su.ics
  tests/cms/utils/test_external_calendar_utils.py
  tests/core/management/commands/assets/calendars/outlook_calendar.ics
  tests/core/management/commands/test_import_events.py
Labels: prio: high, blocker

#3283 Add tests for contact actions
  tests/cms/models/contacts/test_contacts.py
  tests/cms/views/contacts/test_contact_actions.py
Labels: effort: low

#3169 [2024-11-07] TinyMCE: Insert contact, but track using linkcheck
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/models/pois/poi.py
  integreat_cms/cms/models/pois/poi_translation.py
  integreat_cms/cms/templates/_related_contents_table.html
  integreat_cms/cms/templates/_tinymce_config.html
  integreat_cms/cms/templates/ajax_poi_form/_poi_address_container.html
  integreat_cms/cms/templates/contacts/contact_card.html
  integreat_cms/cms/templates/organizations/organization_form.html
  integreat_cms/cms/templatetags/svg_tags.py
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/utils/content_utils.py
  integreat_cms/cms/utils/internal_link_checker.py
  integreat_cms/cms/views/contacts/contact_form_view.py
  integreat_cms/cms/views/utils/__init__.py
  integreat_cms/cms/views/utils/contact_utils.py
  integreat_cms/core/signals/__init__.py
  integreat_cms/core/signals/contact_signals.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/css/contact_card.css
  integreat_cms/static/src/css/style.scss
  integreat_cms/static/src/css/tinymce_custom.css
  integreat_cms/static/src/css/tomselect.scss
  integreat_cms/static/src/editor_content.ts
  integreat_cms/static/src/js/forms/tinymce-init.ts
  integreat_cms/static/src/js/tinymce-plugins/custom_contact_input/plugin.js
  integreat_cms/static/src/js/tinymce-plugins/custom_link_input/plugin.js
  package-lock.json
  package.json
Labels: prio: urgent, deadline, blocker

#3297 Remove `x Locations/Events selected` string for observer role
  integreat_cms/cms/templates/events/event_list.html
  integreat_cms/cms/templates/pois/poi_list.html
  integreat_cms/cms/templates/pois/poi_list_archived.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3263.yml
Labels: effort: low
