Repository digitalfabrik/integreat-cms, pull requests merged in 2024-03, with the labels that each got.

#2654 Dynamic export formats
  integreat_cms/cms/templates/feedback/region_feedback_list.html
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/feedback/region_feedback_actions.py
  tests/cms/views/feedback/test_region_feedback_actions.py
Labels: feature, prio: low

#2709 Fix error when creating a new POI category
  integreat_cms/cms/forms/poi_categories/poi_category_translation_form.py
  integreat_cms/release_notes/current/unreleased/2708.yml
Labels: prio: high

#2672 Store integreat-cms.log as an artifact after test run in CI
  .circleci/config.yml
  integreat_cms/core/circleci_settings.py
  integreat_cms/core/settings.py
Labels: prio: low

#2701 Add option to translate into Plain German
  example-configs/integreat-cms.ini
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/summ_ai_api/summ_ai_api_client.py
Labels: prio: urgent
