Repository digitalfabrik/integreat-cms, pull requests merged in 2024-08, with the labels that each got.

#2934 Show organization locations
  integreat_cms/cms/models/users/organization.py
  integreat_cms/cms/templates/_related_contents_table.html
  integreat_cms/cms/templates/organizations/organization_form.html
  integreat_cms/cms/templates/organizations/organization_list.html
  integreat_cms/cms/templates/organizations/organization_list_row.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2929.yml
  tests/cms/views/organizations/test_organization_form.py
Labels: :heavy_exclamation_mark: prio: medium

#2963 Fix error at restoring old version
  integreat_cms/cms/templates/content_versions.html
  integreat_cms/release_notes/current/unreleased/2962.yml
  integreat_cms/static/src/js/revisions.ts
Labels: :bangbang: prio: high

#2933 Unifiy calculation of pages (not) ready for mt
  integreat_cms/cms/views/analytics/translation_coverage_view.py
  integreat_cms/cms/views/dashboard/dashboard_view.py
  integreat_cms/cms/views/utils/hix.py
  integreat_cms/release_notes/current/unreleased/2903.yml
  tests/cms/utils/test_disable_hix_post_save_signal.py
  tests/cms/views/utils/test_hix.py
  tests/utils.py
Labels: :heavy_exclamation_mark: prio: medium

#2974 Fix error at creating POI in event form
  integreat_cms/cms/views/pois/poi_form_ajax_view.py
  integreat_cms/release_notes/current/unreleased/2973.yml
  tests/cms/utils/test_disable_hix_post_save_signal.py
Labels: :bangbang: prio: high

#2979 Release `2024.8.1`
  .devcontainer/Dockerfile
  .pre-commit-config.yaml
  README.md
  integreat_cms/cms/templates/_form_language_tabs.html
  integreat_cms/cms/views/analytics/translation_coverage_view.py
  integreat_cms/cms/views/dashboard/dashboard_view.py
  integreat_cms/cms/views/pois/poi_form_ajax_view.py
  integreat_cms/cms/views/utils/hix.py
  integreat_cms/core/signals/hix_signals.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2903.yml
  integreat_cms/release_notes/current/unreleased/2917.yml
  integreat_cms/release_notes/current/unreleased/2918.yml
  integreat_cms/release_notes/current/unreleased/2973.yml
  integreat_cms/static/src/css/style.scss
  integreat_cms/static/src/js/analytics/hix-widget.ts
  integreat_cms/static/src/js/language-tabs.ts
  integreat_cms/static/src/svg/poi-category-icons/mental_health.svg
  integreat_cms/static/src/svg/poi-category-icons/shelter.svg
  integreat_cms/static/src/svg/speech.svg
  integreat_cms/textlab_api/textlab_api_client.py
  pyproject.toml
  tests/cms/utils/test_disable_hix_post_save_signal.py
  tests/cms/views/utils/test_hix.py
  tests/utils.py
  tools/install.sh
Labels: :bangbang: prio: high

#2981 Add menu item "contact" to navigation bar
  integreat_cms/cms/templates/_base.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: :bangbang: prio: high

#2844 Keep internal chat messages internal
  integreat_cms/api/v3/chat/zammad_api.py
Labels: :alarm_clock: deadline

#3027 Fix migration
  integreat_cms/cms/migrations/0099_firebasestatistic.py
Labels: :sos: prio: urgent

#3023 [7.11.24] Extend ajax poi form
  integreat_cms/cms/templates/_poi_query_result.html
  integreat_cms/cms/templates/ajax_poi_form/_poi_form_widget.html
  integreat_cms/cms/templates/ajax_poi_form/poi_box.html
  integreat_cms/cms/templates/events/_event_filter_form.html
  integreat_cms/cms/templates/events/event_form.html
  integreat_cms/cms/views/events/event_actions.py
  integreat_cms/cms/views/pois/poi_form_ajax_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3015.yml
  integreat_cms/static/src/js/events/event-query-pois.ts
Labels: :bangbang: prio: high, :alarm_clock: deadline
