Repository digitalfabrik/integreat-cms, pull requests merged in 2024-07, with the labels that each got.

#2867 Fix HIX value display in the HIX widget
  integreat_cms/cms/templates/hix_widget.html
  integreat_cms/release_notes/current/unreleased/2853.yml
Labels: :bangbang: prio: high

#2850 Refactor `clean_content`
  integreat_cms/cms/forms/custom_content_model_form.py
  integreat_cms/cms/utils/content_utils.py
  tests/cms/utils/test_content_utils.py
Labels: :heavy_exclamation_mark: prio: medium

#2891 Remove 'auth' and 'contenttypes' objects from testdata
  integreat_cms/cms/fixtures/test_data.json
Labels: :heavy_exclamation_mark: prio: medium

#2889 Add link checker to the `to-do-board`
  integreat_cms/cms/templates/dashboard/_todo_dashboard_row.html
  integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
  integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_broken_links_row.html
  integreat_cms/cms/templatetags/tagifnotempty.py
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/dashboard/dashboard_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/2024/2024.7.0/2824.yml
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/dashboard/broken-links.ts
  tests/cms/views/dashboard/test_dashboard.py
Labels: :heavy_exclamation_mark: prio: medium

#2937 Remove notranslate class on toggle off
  integreat_cms/release_notes/current/unreleased/2907.yml
  integreat_cms/static/src/js/forms/tinymce-init.ts
Labels: :bangbang: prio: high

#2941 Change hook in button link
  integreat_cms/cms/views/dashboard/dashboard_view.py
Labels: :sos: prio: urgent
