Repository digitalfabrik/integreat-cms, pull requests merged in 2024-10, with the labels that each got.

#3034 [7.11.24] Add form for contact information
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/__init__.py
  integreat_cms/cms/forms/contacts/__init__.py
  integreat_cms/cms/forms/contacts/contact_form.py
  integreat_cms/cms/migrations/0106_update_contact.py
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/templates/ajax_poi_form/poi_box.html
  integreat_cms/cms/templates/contacts/contact_form.html
  integreat_cms/cms/templates/contacts/contact_list.html
  integreat_cms/cms/templates/contacts/contact_list_row.html
  integreat_cms/cms/templates/pois/poi_form_sidebar/action_box.html
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/contacts/__init__.py
  integreat_cms/cms/views/contacts/contact_actions.py
  integreat_cms/cms/views/contacts/contact_context_mixin.py
  integreat_cms/cms/views/contacts/contact_form_view.py
  integreat_cms/cms/views/contacts/contact_list_view.py
  integreat_cms/cms/views/events/event_context_mixin.py
  integreat_cms/cms/views/regions/region_actions.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/poi_box.ts
Labels: :bangbang: prio: high, :alarm_clock: deadline

#3080 [2024-11-07] Add contact list bulk actions
  integreat_cms/cms/templates/contacts/contact_list.html
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/bulk_action_views.py
  integreat_cms/cms/views/contacts/__init__.py
  integreat_cms/cms/views/contacts/contact_bulk_actions.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: :bangbang: prio: high, :alarm_clock: deadline

#3079 Implement region condition data export
  integreat_cms/cms/models/regions/region.py
  integreat_cms/cms/templates/_base.html
  integreat_cms/cms/templates/region_condition/region_condition.html
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/dashboard/dashboard_view.py
  integreat_cms/cms/views/region_condition/__init__.py
  integreat_cms/cms/views/region_condition/region_condition_actions.py
  integreat_cms/cms/views/region_condition/region_condition_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: :bangbang: prio: high

#3128 [2024-11-07] Fix enter saves form
  integreat_cms/cms/templates/events/external_calendar_form.html
  integreat_cms/cms/templates/organizations/organization_form.html
Labels: prio: high, deadline

#3115 [2024-11-07] Extend user permissions for external calendar column in event list
  integreat_cms/cms/templates/events/event_list.html
  integreat_cms/cms/templates/events/event_list_row.html
Labels: prio: high, deadline

#3075 Refactor repair_tree as utility
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/migrations/0105_treebeard_models_add_deferrable_tree_constraints.py
  integreat_cms/cms/migrations/0106_update_contact.py
  integreat_cms/cms/utils/repair_tree.py
  integreat_cms/cms/utils/shadow_instance.py
  integreat_cms/cms/views/pages/page_actions.py
  integreat_cms/core/management/commands/repair_tree.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/api/expected-outputs/augsburg_de_children.json
  tests/api/expected-outputs/augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_pages.json
  tests/cms/utils/test_repair_tree.py
  tests/core/management/commands/test_repair_tree.py
Labels: prio: urgent

#3116 [2024-11-07] Add created by field to external calendar
  integreat_cms/cms/forms/events/external_calendar_form.py
  integreat_cms/cms/migrations/0107_externalcalendar_author_fields.py
  integreat_cms/cms/models/external_calendars/external_calendar.py
  integreat_cms/cms/templates/events/external_calendar_list.html
  integreat_cms/cms/templates/events/external_calendar_list_row.html
  integreat_cms/cms/views/contacts/contact_form_view.py
  integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: prio: high, deadline

#3123 Normalize custom tinymce icons, re-vectorize no-translate.svg
  integreat_cms/static/src/svg/call.svg
  integreat_cms/static/src/svg/clock.svg
  integreat_cms/static/src/svg/contact.svg
  integreat_cms/static/src/svg/email.svg
  integreat_cms/static/src/svg/group.svg
  integreat_cms/static/src/svg/idea.svg
  integreat_cms/static/src/svg/no-translate.svg
  integreat_cms/static/src/svg/pin.svg
  integreat_cms/static/src/svg/select-down-arrow.svg
  integreat_cms/static/src/svg/speech.svg
  integreat_cms/static/src/svg/www.svg
Labels: prio: low, enhancement
