Repository digitalfabrik/integreat-cms, pull requests merged in 2024-11, with the labels that each got.

#3176 Fix issue template labels
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: infrastructure

#3168 Add tests for contact form
  integreat_cms/cms/fixtures/test_data.json
  tests/cms/models/contacts/test_contacts.py
  tests/cms/views/contacts/test_contact_actions.py
  tests/cms/views/contacts/test_contact_form.py
Labels: effort: low, deadline

#3126 [2024-11-07] Disable copying for imported events
  integreat_cms/cms/models/events/event.py
  integreat_cms/cms/templates/events/event_list_row.html
  integreat_cms/cms/views/events/event_actions.py
  integreat_cms/cms/views/events/event_context_mixin.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/cms/views/events/events.py
Labels: prio: high, deadline

#3203 Fix copying of language tree nodes in the region form
  integreat_cms/cms/forms/regions/region_form.py
Labels: prio: urgent, blocks-release

#3198 Add related issues header for issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: effort: low

#3207 Fix error at bulk action in broken link list
  integreat_cms/cms/templates/linkcheck/links_by_filter.html
  integreat_cms/release_notes/current/unreleased/3118.yml
Labels: effort: low

#3206 Fix display of start and end of archived events
  integreat_cms/cms/templates/events/event_list_archived_row.html
  integreat_cms/release_notes/current/unreleased/3190.yml
Labels: effort: low

#3205 Ical: Add support for recurrence rules
  integreat_cms/cms/constants/frequency.py
  integreat_cms/cms/constants/weekdays.py
  integreat_cms/cms/constants/weeks.py
  integreat_cms/cms/utils/external_calendar_utils.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/core/management/commands/assets/calendars/recurrence_rules.ics
  tests/core/management/commands/assets/calendars/single_recurring_event_a.ics
  tests/core/management/commands/assets/calendars/single_recurring_event_b.ics
  tests/core/management/commands/test_import_events.py
Labels: deadline

#3221 Revive export box of statistics
  integreat_cms/cms/templates/statistics/statistics_overview.html
  integreat_cms/cms/templates/statistics/statistics_sidebar.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3131.yml
Labels: blocks-release

#3220 Fix false positiv error message in statistics in dashboard
  integreat_cms/release_notes/current/unreleased/3213.yml
  integreat_cms/static/src/js/analytics/statistics-charts.ts
Labels: blocks-release

#3243 Fix release note of fax icon
  integreat_cms/release_notes/current/unreleased/3225.yml
Labels: blocks-release

#3235 Document how to debug with PyCharm
  docs/src/debugging.rst
  docs/src/images/debugging/debug-pycharm-01-django-config.png
Labels: effort: low

#3242 Add tests for organization actions
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/views/organizations/organization_actions.py
  integreat_cms/cms/views/organizations/organization_bulk_actions.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/cms/views/organizations/test_organization_actions.py
  tests/cms/views/organizations/test_organization_form.py
Labels: effort: low

#3191 Improve link checker GUI
  integreat_cms/cms/templates/linkcheck/links_by_filter.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2588.yml
Labels: effort: low

#3162 [2024-11-07] Show related contacts in the POI form
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/cms/templates/pois/poi_form_sidebar/action_box.html
  integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/cms/views/poi/test_poi_form.py
Labels: deadline
