Repository digitalfabrik/integreat-cms, pull requests merged in 2024-06, with the labels that each got.

#2391 Add API for social media tags
  docs/src/api-docs.rst
  integreat_cms/api/urls.py
  integreat_cms/api/v3/social_media_headers.py
  integreat_cms/api/v3/templates/error_headers.html
  integreat_cms/api/v3/templates/social_media_headers.html
  integreat_cms/api/v3/templates/webapp_server_side_include.html
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/languages/language_form.py
  integreat_cms/cms/migrations/0092_social_media_fields.py
  integreat_cms/cms/models/languages/language.py
  integreat_cms/cms/templates/languages/language_form.html
  integreat_cms/cms/utils/internal_link_utils.py
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/2023/unreleased/2391.yml
  integreat_cms/static/src/logos/aschaffenburg/social-media-preview.png
  integreat_cms/static/src/logos/integreat/social-media-preview.png
  integreat_cms/static/src/logos/malte/social-media-preview.png
  integreat_cms/static/src/logos/netzwerk-obdach/social-media-preview.png
  pyproject.toml
  tests/api/api_config.py
  tests/api/expected-outputs/social.html
  tests/api/expected-outputs/social_augsburg.html
  tests/api/expected-outputs/social_augsburg_de.html
  tests/api/expected-outputs/social_augsburg_de_child_page.html
  tests/api/expected-outputs/social_augsburg_de_event.html
  tests/api/expected-outputs/social_augsburg_de_event_non-existing.html
  tests/api/expected-outputs/social_augsburg_de_location.html
  tests/api/expected-outputs/social_augsburg_de_location_non-existing.html
  tests/api/expected-outputs/social_augsburg_de_page.html
  tests/api/expected-outputs/social_augsburg_de_page_non-existing.html
  tests/api/expected-outputs/social_augsburg_de_pn.html
  tests/api/expected-outputs/social_augsburg_de_pn_non-existing.html
  tests/api/expected-outputs/social_augsburg_non-existing.html
  tests/api/expected-outputs/social_landing.html
  tests/api/expected-outputs/social_landing_de.html
  tests/api/expected-outputs/social_landing_en.html
  tests/api/expected-outputs/social_landing_non-existing.html
  tests/api/test_api_social.py
  tests/cms/views/view_config.py
Labels: :bangbang: prio: high

#2819 Update dependencies
  .pre-commit-config.yaml
  integreat_cms/cms/utils/media_utils.py
  package-lock.json
  package.json
  pyproject.toml
Labels: :bangbang: prio: high

#2219 Clean-up translation version history
  integreat_cms/cms/models/abstract_content_translation.py
  integreat_cms/cms/views/pages/page_form_view.py
  integreat_cms/release_notes/current/unreleased/2067.yml
  tests/cms/views/pages/test_page_translations.py
Labels: :heavy_exclamation_mark: prio: medium

#2839 Hotfix: Add default for language color in language model
  integreat_cms/cms/migrations/0094_add_default_language_color.py
  integreat_cms/cms/models/languages/language.py
Labels: :bug: bug, :sos: prio: urgent

#2841 Merge migrations
  integreat_cms/cms/migrations/0093_language_language_color.py
  integreat_cms/cms/migrations/0094_add_default_language_color.py
Labels: :bug: bug, :sos: prio: urgent

#2738 [14.06.] Implement Chat API
  docs/src/api-docs.rst
  integreat_cms/api/urls.py
  integreat_cms/api/v3/chat/__init__.py
  integreat_cms/api/v3/chat/user_chat.py
  integreat_cms/api/v3/chat/zammad_api.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/regions/region_form.py
  integreat_cms/cms/migrations/0094_add_userchat_fields.py
  integreat_cms/cms/models/__init__.py
  integreat_cms/cms/models/chat/__init__.py
  integreat_cms/cms/models/chat/attachment_map.py
  integreat_cms/cms/models/chat/user_chat.py
  integreat_cms/cms/models/regions/region.py
  integreat_cms/cms/templates/regions/region_form.html
  integreat_cms/core/context_processors.py
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/2619.yml
  pyproject.toml
  tests/api/test_api_chat.py
Labels: :bangbang: prio: high, :alarm_clock: deadline

#2851 Release `2024.6.1`
  .eslintrc.js
  .pre-commit-config.yaml
  docs/src/api-docs.rst
  integreat_cms/api/urls.py
  integreat_cms/api/v3/chat/__init__.py
  integreat_cms/api/v3/chat/user_chat.py
  integreat_cms/api/v3/chat/zammad_api.py
  integreat_cms/cms/constants/colors.py
  integreat_cms/cms/constants/language_color.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/custom_content_model_form.py
  integreat_cms/cms/forms/languages/language_form.py
  integreat_cms/cms/forms/regions/region_form.py
  integreat_cms/cms/migrations/0093_language_language_color.py
  integreat_cms/cms/migrations/0094_add_userchat_fields.py
  integreat_cms/cms/models/__init__.py
  integreat_cms/cms/models/abstract_content_translation.py
  integreat_cms/cms/models/chat/__init__.py
  integreat_cms/cms/models/chat/attachment_map.py
  integreat_cms/cms/models/chat/user_chat.py
  integreat_cms/cms/models/languages/language.py
  integreat_cms/cms/models/regions/region.py
  integreat_cms/cms/templates/languages/language_form.html
  integreat_cms/cms/templates/languages/language_list.html
  integreat_cms/cms/templates/languages/language_list_row.html
  integreat_cms/cms/templates/languagetreenodes/languagetreenode_form.html
  integreat_cms/cms/templates/languagetreenodes/languagetreenode_list.html
  integreat_cms/cms/templates/languagetreenodes/languagetreenode_list_row.html
  integreat_cms/cms/templates/regions/region_form.html
  integreat_cms/cms/views/dashboard/dashboard_view.py
  integreat_cms/cms/views/media/media_context_mixin.py
  integreat_cms/cms/views/pages/page_form_view.py
  integreat_cms/core/context_processors.py
  integreat_cms/core/settings.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/matomo_api/matomo_api_client.py
  integreat_cms/release_notes/current/unreleased/2067.yml
  integreat_cms/release_notes/current/unreleased/2390.yml
  integreat_cms/release_notes/current/unreleased/246.yml
  integreat_cms/release_notes/current/unreleased/2619.yml
  integreat_cms/release_notes/current/unreleased/2623.yml
  integreat_cms/release_notes/current/unreleased/2724.yml
  integreat_cms/release_notes/current/unreleased/2834.yml
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/analytics/statistics-charts.ts
  integreat_cms/static/src/js/events/conditional-fields.ts
  integreat_cms/static/src/js/languages/language-color-fields.ts
  integreat_cms/static/src/js/media-management/component/upload-file.tsx
  integreat_cms/static/src/js/media-management/index.tsx
  integreat_cms/static/src/js/media-management/library.tsx
  integreat_cms/static/src/js/media-management/select-media.tsx
  package-lock.json
  package.json
  pyproject.toml
  tests/api/test_api_chat.py
  tests/cms/views/pages/test_page_translations.py
  tests/cms/views/view_config.py
  tools/_functions.sh
  tools/vitest.sh
Labels: :bangbang: prio: high

#2846 Add A/B testing for the Integreat Chat
  docs/src/api-docs.rst
  integreat_cms/api/urls.py
  integreat_cms/api/v3/chat/user_chat.py
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/regions/region_form.py
  integreat_cms/cms/migrations/0096_chat_beta_testing.py
  integreat_cms/cms/models/__init__.py
  integreat_cms/cms/models/chat/user_chat.py
  integreat_cms/cms/models/regions/region.py
  integreat_cms/cms/templates/regions/region_form.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/api/test_api_chat.py
Labels: :alarm_clock: deadline

#2636 Update page link before submitting page form
  integreat_cms/cms/models/users/user.py
  integreat_cms/cms/templates/events/event_form.html
  integreat_cms/cms/templates/imprint/imprint_form.html
  integreat_cms/cms/templates/pages/page_form.html
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/cms/views/pages/page_tree_view.py
  integreat_cms/cms/views/utils/slugify_ajax.py
  integreat_cms/static/src/js/forms/prevent-premature-submission.ts
  integreat_cms/static/src/js/forms/update-permalink.ts
  tests/cms/views/view_config.py
Labels: :bug: bug, :heavy_exclamation_mark: prio: medium

#2878 Fix feedback display
  integreat_cms/release_notes/current/unreleased/2877.yml
  integreat_cms/static/src/js/analytics/hix-widget.ts
Labels: :bangbang: prio: high
