Repository digitalfabrik/integreat-cms, pull requests merged in 2024-05, with the labels that each got.

#2768 Add possibility to import locations from CSV files
  integreat_cms/cms/models/abstract_content_model.py
  integreat_cms/core/management/commands/import_pois_from_csv.py
  integreat_cms/release_notes/current/unreleased/2757.yml
  tests/core/management/commands/assets/pois_to_import.csv
Labels: prio: urgent

#2770 Re-add barrier-free and organization box to POI
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/release_notes/current/unreleased/2769.yml
  tests/cms/views/poi/test_poi_form.py
Labels: bug

#2761 Provide HIX feedback details
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/forms/pages/page_translation_form.py
  integreat_cms/cms/migrations/0090_pagetranslation_hix_feedback.py
  integreat_cms/cms/models/pages/page_translation.py
  integreat_cms/cms/templates/hix_widget.html
  integreat_cms/cms/views/utils/hix.py
  integreat_cms/core/signals/hix_signals.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/js/analytics/hix-widget.ts
  integreat_cms/textlab_api/textlab_api_client.py
  tests/cms/test_duplicate_regions.py
  tests/textlab_api/textlab_api_test.py
Labels: :bangbang: prio: high

#2784 Mark locations as closed by default during CSV import
  integreat_cms/core/management/commands/import_pois_from_csv.py
  integreat_cms/release_notes/current/unreleased/2783.yml
  tests/core/management/commands/assets/pois_to_import.csv
Labels: :bangbang: prio: high

#2781 Fix loadtestdata not working after adding a new model
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/core/signals/feedback_signals.py
  integreat_cms/core/signals/hix_signals.py
  integreat_cms/core/signals/organization_signals.py
  integreat_cms/core/utils/decorators.py
Labels: :bug: bug, :sos: prio: urgent
