Repository digitalfabrik/integreat-cms, pull requests merged in 2025-01, with the labels that each got.

#3299 Fix: prevent early exit of tools/code_style.sh after exit code 1
  tools/code_style.sh
Labels: not-testable

#3292 Stop hiding the grids when POI is removed
  integreat_cms/cms/templates/ajax_poi_form/poi_box.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/poi-box.ts
Labels: prio: high, deadline

#3273 Support rrules with `BYDAY` frequencies
  integreat_cms/cms/utils/external_calendar_utils.py
  tests/cms/utils/assets/calendars/invalid_recurrence_rule_conflicting_byday_and_bysetpos.ics
  tests/cms/utils/assets/calendars/invalid_recurrence_rule_multiple_byday_frequencies.ics
  tests/cms/utils/test_external_calendar_utils.py
  tests/core/management/commands/assets/calendars/recurrence_rules.ics
  tests/core/management/commands/test_import_events.py
Labels: prio: high, deadline, blocker

#3282 Prevent orphaned contact cards
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/templates/contacts/contact_card.html
  integreat_cms/cms/templates/contacts/contact_form.html
  integreat_cms/cms/views/contacts/contact_actions.py
  integreat_cms/cms/views/contacts/contact_bulk_actions.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/css/contact_card.css
  tests/api/api_config.py
  tests/api/expected-outputs/augsburg_de_children.json
  tests/api/expected-outputs/augsburg_de_children_archived_descendants.json
  tests/api/expected-outputs/augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_pages.json
  tests/cms/models/contacts/test_contacts.py
  tests/cms/test_duplicate_regions.py
  tests/cms/views/contacts/test_contact_actions.py
  tests/cms/views/poi/test_poi_form.py
  tests/pdf/files/89219cf973/Integreat - Deutsch - Augsburg.pdf
  tests/pdf/test_pdf_export.py
  tests/sitemap/expected-sitemaps/sitemap-augsburg-de.xml
  tests/sitemap/sitemap_config.py
Labels: deadline

#3340 Make `eslint` catch `console.log` statements
  .eslintrc.js
  integreat_cms/static/src/js/media-management/component/edit-sidebar.tsx
Labels: not-testable

#3313 Add release note for external calendars
  integreat_cms/release_notes/current/unreleased/100.yml
Labels: blocker

#3353 Change translation of ical filter
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: prio: urgent, blocks-release

#3334 Sort contacts by group and name
  integreat_cms/cms/migrations/0112_sort_contacts_by_POI_and_name.py
  integreat_cms/cms/models/contact/contact.py
Labels: effort: low, deadline

#3196 Add contact creation in POI form
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/contacts/__init__.py
  integreat_cms/cms/views/contacts/contact_form_ajax_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/static/src/index.ts
  integreat_cms/static/src/js/ajax-contact-form.ts
Labels: prio: high, deadline

#3117 Test/bulk cancel translation process
  integreat_cms/cms/fixtures/test_data.json
  tests/api/api_config.py
  tests/api/expected-outputs/augsburg_de_children.json
  tests/api/expected-outputs/augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_pages.json
  tests/cms/utils/test_cancel_translation.py
  tests/cms/views/dashboard/test_dashboard.py
  tests/pdf/files/990a572a06/Integreat - Deutsch - Augsburg.pdf
  tests/pdf/test_pdf_export.py
  tests/sitemap/expected-sitemaps/sitemap-augsburg-de.xml
  tests/sitemap/expected-sitemaps/sitemap-augsburg-en.xml
  tests/sitemap/sitemap_config.py
Labels: effort: low

#3352 Refactor/update icalendar
  integreat_cms/cms/utils/external_calendar_utils.py
  pyproject.toml
Labels: not-testable

#3363 Move translation coverage and change text
  integreat_cms/cms/templates/dashboard/_todo_dashboard_widget.html
  integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_missing_translations_row.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: effort: low, blocks-release

#3375 Fix contact link tracking
  flake.nix
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/utils/internal_link_checker.py
  tests/api/expected-outputs/augsburg_de_children.json
  tests/api/expected-outputs/augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_pages.json
Labels: prio: high, effort: low, deadline

#3335 Startup redis server in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: not-testable
