Repository digitalfabrik/integreat-cms, pull requests merged in 2025-06, with the labels that each got.

#3395 tools/ruff.sh: Allow restricting checking to specific subtrees
  tools/ruff.sh
  tools/ruff_check.sh
  tools/ruff_format.sh
Labels: infrastructure, enhancement, not-testable

#3752 Remove the release note for #3626
  integreat_cms/release_notes/current/unreleased/3626.yml
Labels: blocks-release

#3761 return new Contact record from copy method
  integreat_cms/cms/models/contact/contact.py
Labels: not-testable
