Repository digitalfabrik/integreat-cms, pull requests merged in 2025-02, with the labels that each got.

#3368 Add release note for translation coverage on dashboard
  integreat_cms/release_notes/current/unreleased/4.yml
Labels: effort: low, blocks-release

#3364 Rename offline app to phone/mobile app
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/matomo_api/matomo_api_client.py
Labels: effort: low

#3393 docs: update tools.rst
  docs/src/tools.rst
Labels: documentation

#3402 Fixes pagination and adds administrative division to region condition
  integreat_cms/cms/templates/region_condition/region_condition.html
  integreat_cms/cms/templates/region_condition/region_condition_row.html
  integreat_cms/cms/views/region_condition/region_condition_actions.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: effort: low

#3404 send_push_notifications: 1–based counting, improve messages
  integreat_cms/cms/models/push_notifications/push_notification.py
  integreat_cms/cms/models/push_notifications/push_notification_translation.py
  integreat_cms/core/management/commands/send_push_notifications.py
  integreat_cms/firebase_api/firebase_api_client.py
Labels: infrastructure, enhancement

#3417 Fix typo when inserting contact card
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: effort: low

#3412 Fix minor translation error
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/cms/views/regions/delete_region.py
Labels: effort: low

#3419 Fix console error for long term events
  integreat_cms/static/src/js/event-duration.ts
Labels: effort: low

#3428 Fix recurrence end date
  integreat_cms/cms/views/events/event_form_view.py
Labels: prio: high, blocks-release

#3438 Fix typo in imprint form
  integreat_cms/cms/templates/imprint/imprint_form.html
Labels: effort: low

#3432 Reject all daily events in import
  integreat_cms/cms/utils/external_calendar_utils.py
  tests/core/management/commands/test_import_events.py
Labels: prio: high, effort: low, blocks-release

#3446 Finalize contact permissions
  integreat_cms/cms/constants/roles.py
  integreat_cms/release_notes/current/unreleased/2955.yml
  tests/cms/views/contacts/test_contact_actions.py
  tests/cms/views/contacts/test_contact_form.py
  tests/cms/views/poi/test_poi_form.py
Labels: blocks-release

#3442 Hide contact links and contact cards from the linkchecker
  integreat_cms/cms/utils/linkcheck_utils.py
  tests/cms/test_duplicate_regions.py
Labels: prio: high, deadline, blocks-release

#3454 Fix german translation in contact suggestion
  integreat_cms/cms/templates/contacts/contact_from_email_and_phone_row.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: prio: high, effort: low, blocks-release

#3455 Update permission setting for contact
  integreat_cms/cms/migrations/0115_update_contact_permission.py
Labels: prio: high, blocks-release

#3468 Fix hix color code
  integreat_cms/release_notes/current/unreleased/3467.yml
  integreat_cms/static/src/js/analytics/hix-widget.ts
Labels: effort: low
