Repository digitalfabrik/integreat-cms, pull requests merged in 2025-03, with the labels that each got.

#3469 Deliver all contacts of a poi to API
  docs/src/api-docs.rst
  integreat_cms/api/v3/locations.py
  integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
  integreat_cms/cms/templates/contacts/contact_form.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3460.yml
  integreat_cms/release_notes/current/unreleased/3462.yml
  tests/api/api_config.py
  tests/api/expected-outputs/augsburg_ar_locations.json
  tests/api/expected-outputs/augsburg_de_locations.json
  tests/api/expected-outputs/augsburg_en_locations.json
  tests/api/expected-outputs/nurnberg_de_locations.json
  tests/api/expected-outputs/nurnberg_en_locations.json
Labels: prio: high, blocks-app

#3410 Adjust filters for long term events
  integreat_cms/cms/constants/recurrence.py
  integreat_cms/cms/forms/events/event_filter_form.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3379.yml
  tests/cms/views/events/test_event_filter.py
Labels: prio: medium

#3474 Add beta permission
  integreat_cms/cms/constants/roles.py
  integreat_cms/cms/fixtures/test_roles.json
  integreat_cms/cms/migrations/0117_add_beta_permission.py
  integreat_cms/cms/models/users/user.py
Labels: blocker

#3485 Fix search term being cleared after search in event filter
  integreat_cms/cms/forms/events/event_filter_form.py
Labels: prio: high, blocks-release

#3478 Fix wording of weekdays and translation of recurring
  integreat_cms/cms/migrations/0117_rename_weekdays_in_events.py
  integreat_cms/cms/models/events/event.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3436.yml
  integreat_cms/release_notes/current/unreleased/3437.yml
Labels: prio: medium

#3495 Fix the migration order
  integreat_cms/cms/migrations/0118_rename_weekdays_in_events.py
Labels: prio: urgent, blocker, blocks-release

#3392 Pytest: Enable using markers
  tools/test.sh
Labels: bug, infrastructure

#3499 Revert fax number in contact
  integreat_cms/cms/forms/contacts/contact_form.py
  integreat_cms/cms/migrations/0120_remove_fax_number_from_contact.py
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
  integreat_cms/cms/templates/contacts/contact_card.html
  integreat_cms/cms/templates/contacts/contact_form.html
  integreat_cms/cms/templates/contacts/contact_list.html
  integreat_cms/cms/templates/contacts/contact_list_row.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3473.yml
  tests/cms/views/contacts/test_contact_form.py
Labels: prio: high, blocks-release

#3505 Fix the german translation for phone number warning and remove "fax" from the release note
  integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
  integreat_cms/cms/templates/contacts/contact_form.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3473.yml
Labels: prio: high, blocks-release

#3415 Move automatically saved note
  integreat_cms/cms/templates/events/event_form.html
  integreat_cms/cms/templates/pages/page_form.html
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/release_notes/current/unreleased/3327.yml
Labels: bug, effort: low

#3507 Add possibility to create a contact while a new POI being created
  integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
  integreat_cms/cms/templates/pois/poi_form.html
  integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
  integreat_cms/cms/views/pois/poi_form_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3322.yml
  integreat_cms/static/src/js/ajax-contact-form.ts
Labels: prio: high

#3479 Fix contact doesn't show up in search when searching for address
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/release_notes/current/unreleased/3464.yml
  tests/cms/views/contacts/test_contact_utils.py
Labels: bug

#3531 Hide the button for ajax contact creation when POI is archived
  integreat_cms/cms/forms/contacts/contact_form.py
  integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3523.yml
Labels: effort: low

#3535 Improve loading time for creating new user
  integreat_cms/cms/views/utils/user.py
Labels: prio: high

#3543 Update twine to continue being able to upload packages to pypi
  pyproject.toml
Labels: bug, infrastructure, dependencies, prio: urgent, blocks-release

#3487 Extend test for event
  tests/cms/views/events/test_event_form.py
Labels: not-testable
