Repository digitalfabrik/integreat-cms, pull requests merged in 2025-04, with the labels that each got.

#3569 Do not count excluded content attributes towards translation budget
  integreat_cms/cms/constants/machine_translatable_attributes.py
  integreat_cms/cms/templates/_machine_translation_overlay.html
  integreat_cms/cms/views/utils/machine_translations.py
  integreat_cms/core/utils/machine_translation_api_client.py
  integreat_cms/core/utils/word_count.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  tests/mt_api/utils.py
Labels: blocks-release

#3575 Update issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: not-testable

#3582 Add release note for #3071
  integreat_cms/release_notes/current/unreleased/3071.yml
Labels: blocks-release

#3577 Allow svg uploads in media library
  .circleci/config.yml
  .devcontainer/Dockerfile
  README.md
  docs/src/installation.rst
  flake.nix
  integreat_cms/cms/constants/allowed_media.py
  integreat_cms/cms/migrations/0123_allow_svg_uploads.py
  integreat_cms/cms/utils/media_utils.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3583.yml
  pyproject.toml
Labels: prio: urgent, blocks-release

#3231 Add popup for information about page access statistics [Wait for #3130]
  integreat_cms/cms/fixtures/test_data.json
  integreat_cms/cms/migrations/0125_add_statistics_tutorial_seen_to_user.py
  integreat_cms/cms/models/users/user.py
  integreat_cms/cms/templates/generic_tutorial_dialog.html
  integreat_cms/cms/templates/pages/pages_page_tree.html
  integreat_cms/cms/templates/statistics/statistics_overview.html
  integreat_cms/cms/templates/statistics/statistics_viewed_pages.html
  integreat_cms/cms/templates/tutorials/page_access_statistics.html
  integreat_cms/cms/views/pages/page_tree_view.py
  integreat_cms/cms/views/settings/dismiss_tutorial_view.py
  integreat_cms/cms/views/statistics/statistics_view.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3132.yml
Labels: blocked

#3601 Fix edit icon in the page tree
  integreat_cms/cms/templates/pages/pages_page_tree_node.html
Labels: prio: high, effort: low

#3606 Add release note for #3066
  integreat_cms/release_notes/current/unreleased/3066.yml
Labels: effort: low

#3602 Fix archive/restore icons in page tree
  integreat_cms/cms/templates/pages/pages_page_tree_node.html
Labels: prio: high, effort: low

#3608 Fix statistics graph sizing
  integreat_cms/cms/templates/statistics/_statistics_widget.html
Labels: prio: high, effort: low

#3617 Re-add warning for mobile phone
  integreat_cms/cms/templates/ajax_contact_form/_contact_form_widget.html
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3591.yml
Labels: blocks-release

#3620 fix: migration history, move 124->126
  integreat_cms/cms/migrations/0126_region_summ_ai_budget_used_and_more.py
Labels: prio: high, effort: low

#3619 Fix pagination in language list
  integreat_cms/cms/templates/languages/language_list.html
Labels: effort: low

#3618 Disable Matomo tracking for test servers
  integreat_cms/api/decorators.py
Labels: prio: high

#3502 Fix gettext/msgformat errors
  integreat_cms/cms/views/bulk_action_views.py
  integreat_cms/cms/views/contacts/contact_bulk_actions.py
  integreat_cms/cms/views/organizations/organization_bulk_actions.py
  integreat_cms/cms/views/pages/page_bulk_actions.py
  integreat_cms/cms/views/utils/publication_status.py
  integreat_cms/core/utils/machine_translation_api_client.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/summ_ai_api/summ_ai_api_client.py
Labels: infrastructure

#3164 Sort news/push notifications
  docs/src/api-docs.rst
  integreat_cms/api/v3/push_notifications.py
Labels: effort: low, stale

#3631 Hide page based statistics
  integreat_cms/cms/constants/roles.py
  integreat_cms/cms/fixtures/test_roles.json
  integreat_cms/cms/migrations/0127_hide_page_based_statistics.py
  integreat_cms/cms/models/users/user.py
  integreat_cms/cms/templates/statistics/statistics_overview.html
Labels: prio: high, effort: low, blocks-release

#3636 Delete release note for statistics popup
  integreat_cms/release_notes/current/unreleased/3132.yml
Labels: blocks-release
