Repository digitalfabrik/integreat-cms, pull requests merged in 2025-08, with the labels that each got.

#3805 Fix the test coverage reporting failure
  .circleci/config.yml
Labels: not-testable

#3830 Release `2025.8.1`
  integreat_cms/cms/forms/regions/region_form.py
  integreat_cms/release_notes/current/unreleased/3829.yml
Labels: prio: high

#3841 Fix page submit button
  integreat_cms/cms/templates/pages/page_form.html
Labels: prio: urgent, blocks-release

#3851 API events: Fix internal server error
  integreat_cms/api/v3/locations.py
  integreat_cms/release_notes/current/unreleased/3776.yml
Labels: prio: urgent

#3749 Fetch page accesses with celery
  docs/src/management-commands.rst
  integreat_cms/cms/views/statistics/statistics_actions.py
  integreat_cms/core/management/commands/fetch_page_accesses.py
  integreat_cms/integreat_celery/celery.py
  integreat_cms/matomo_api/matomo_api_client.py
  integreat_cms/matomo_api/utils.py
Labels: prio: high
