Repository digitalfabrik/integreat-cms, pull requests merged in 2025-05, with the labels that each got.

#3594 Add search function to region conditions
  integreat_cms/cms/templates/region_condition/region_condition.html
  integreat_cms/cms/views/region_condition/region_condition_view.py
  integreat_cms/cms/views/utils/search_content_ajax.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3593.yml
Labels: effort: low, blocker

#3622 Add search function to contact list
  integreat_cms/cms/models/contact/contact.py
  integreat_cms/cms/templates/contacts/contact_list.html
  integreat_cms/cms/views/contacts/contact_list_view.py
  integreat_cms/cms/views/utils/search_content_ajax.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
  integreat_cms/release_notes/current/unreleased/3484.yml
Labels: blocker

#3651 Fix internal server error in suggest contacts
  integreat_cms/cms/urls/protected.py
  integreat_cms/cms/views/contacts/contact_from_existing_data.py
  integreat_cms/core/management/commands/fix_internal_links.py
  tests/cms/views/contacts/test_contact_from_existing_data.py
Labels: prio: high, blocks-release

#3650 Fix linkcheck tests for CI pipeline
  integreat_cms/cms/fixtures/test_data.json
  tests/api/expected-outputs/augsburg_de_children.json
  tests/api/expected-outputs/augsburg_de_children_depth_2.json
  tests/api/expected-outputs/augsburg_de_pages.json
  tests/cms/test_duplicate_regions.py
  tests/cms/views/link_replace/test_link_actions.py
Labels: prio: urgent, blocker, blocks-release

#3675 Fix timeout during loading central linkchecker
  integreat_cms/cms/utils/linkcheck_utils.py
Labels: prio: high

#3678 Fix migration file #130
  integreat_cms/cms/migrations/0131_add_automatical_feedback_to_searchresultfeedback.py
Labels: prio: high, blocker, not-testable

#3671 Fix test_find_missing_versions_failure
  tests/core/management/commands/test_find_missing_versions.py
Labels: not-testable

#3390 Add management command to update link text
  docs/src/management-commands.rst
  integreat_cms/core/management/commands/update_link_text.py
  tests/core/management/commands/test_update_link_text.py
Labels: not-testable

#3688 Add page accesses model
  integreat_cms/cms/migrations/0133_add_page_accesses.py
  integreat_cms/cms/models/__init__.py
  integreat_cms/cms/models/regions/region.py
  integreat_cms/cms/models/statistics/__init__.py
  integreat_cms/cms/models/statistics/page_accesses.py
  integreat_cms/locale/de/LC_MESSAGES/django.po
Labels: prio: high
